export const login = {
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
};

export const logout = {
    LOGIN_START: "LOGOUT_START",
    LOGIN_SUCCESS: "LOGOUT_SUCCESS",
    LOGIN_ERROR: "LOGOUT_ERROR",
};

export const register = {
    REGISTER_START: "REGISTER_START",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_ERROR: "REGISTER_ERROR",
};

export const addPost = {
    ADD_POST_START: "ADD_POST_START",
    ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
    ADD_POST_ERROR: "ADD_POST_ERROR",
};

export const updPost = {
    UPD_POST_START: "UPD_POST_START",
    UPD_POST_SUCCESS: "UPD_POST_SUCCESS",
    UPD_POST_ERROR: "UPD_POST_ERROR",
};

export const delPost = {
    DEL_POST_START: "DEL_POST_START",
    DEL_POST_SUCCESS: "DEL_POST_SUCCESS",
    DEL_POST_ERROR: "DEL_POST_ERROR",
};

export const likePost = {
    LIKE_POST_START: "LIKE_POST_START",
    LIKE_POST_SUCCESS: "LIKE_POST_SUCCESS",
    LIKE_POST_ERROR: "LIKE_POST_ERROR",
};

export const getPost = {
    GET_POST_START: "GET_POST_START",
    GET_POST_SUCCESS: "GET_POST_SUCCESS",
    GET_POST_ERROR: "GET_POST_ERROR",
};

export const getAllPosts = {
    GET_ALL_POSTS_START: "GET_ALL_POSTS_START",
    GET_ALL_POSTS_SUCCESS: "GET_ALL_POSTS_SUCCESS",
    GET_ALL_POSTS_ERROR: "GET_ALL_POSTS_ERROR",
};

export const updUser = {
    UPD_USER_START: "UPD_USER_START",
    UPD_USER_SUCCESS: "UPD_USER_SUCCESS",
    UPD_USER_ERROR: "UPD_USER_ERROR",
};

export const delUser = {
    DEL_USER_START: "DEL_USER_START",
    DEL_USER_SUCCESS: "DEL_USER_SUCCESS",
    DEL_USER_ERROR: "DEL_USER_ERROR",
};

export const getUser = {
    GET_USER_START: "GET_USER_START",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_ERROR: "GET_USER_ERROR",
};

export const followUser = {
    FOLLOW_USER_START: "FOLLOW_USER_START",
    FOLLOW_USER_SUCCESS: "FOLLOW_USER_SUCCESS",
    FOLLOW_USER_ERROR: "FOLLOW_USER_ERROR",
};

export const unfollowUser = {
    UNFOLLOW_USER_START: "UNFOLLOW_USER_START",
    UNFOLLOW_USER_SUCCESS: "UNFOLLOW_USER_SUCCESS",
    UNFOLLOW_USER_ERROR: "UNFOLLOW_USER_ERROR",
};
